version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: convertor-frontend:latest
    container_name: convertor-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - convertor-net

networks:
  convertor-net:
    name: convertor-network
